### ISSUE TITLE
Widths for react-select 

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-pub-ui#103]
Currently, the width of the `react-select` component is `100%` of the available UI. This leaves a lot of white space in all cases, state and MSA/MD lists. (We'll be listing the reports instead of using `react-select`.)

Come up with a way to handle these widths a little better, to make them more like an HTML `<Select>` .

---

This doesn't seem a straightforward as I hoped.

https://github.com/JedWatson/react-select/issues/323
https://stackoverflow.com/questions/46571811/react-select-auto-size-width

The best option may be to put a wrapper around the component with something like 

```css
.select-wrapper {
  width: <whatever we determine>px;
  max-width: 100%;
}
```
